version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOSTNAME=mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.3
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
